### PR TITLE
Jmx monitoring

### PR DESCRIPTION
**Pull request by kjgarza**
This change is [Reviewable](https://reviewable.io/reviews/datacite/search/153)

### CODE REVIEW

**Comment by mfenner** [comment]
Is this pull request not just about monitoring, but also about a deployable master branch? Which makes a lot of sense.

**Comment by kjgarza** [comment]
I actually didn't notice (i.e. forgot) that we were not using `master`. Agree it makes sense to back to using the branch.

**Comment by mfenner** [comment]
Maybe add jmx_monitoring to the branch that is currently deployed and do the fixing of `master` separately.

**Comment by richardhallett** [comment]
Reviewed 3 of 4 files at r1, 5 of 5 files at r2.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/datacite/search/153)*

**Comment by mfenner** [comment]
:lgtm:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/datacite/search/153#-:-L-H7kA22MJ-VKvGE7JW:bnfp4nl)*

**Pull request merged**
