### PR TITLE
Limit start to avoid deep-pagination problems

### PR DESCRIPTION
**Pull request by kjgarza**
it should not allow you to go beyond record 999999

It will pass with
> api?q=*:*&rows=50&start=999999&sort=updated%20asc&fq=updated:[0001-01-01T00:00:00Z%20TO%209999-12-31T23:59:59Z]

it will fail with
> api?q=*:*&rows=50&start=9999999&sort=updated%20asc&fq=updated:[0001-01-01T00:00:00Z%20TO%209999-12-31T23:59:59Z]

### CODE REVIEW

**Comment by kjgarza** [comment]
it should not allow you to go beyond record 999999

It will pass with
> api?q=*:*&rows=50&start=999999&sort=updated%20asc&fq=updated:[0001-01-01T00:00:00Z%20TO%209999-12-31T23:59:59Z]

it will fail with
> api?q=*:*&rows=50&start=9999999&sort=updated%20asc&fq=updated:[0001-01-01T00:00:00Z%20TO%209999-12-31T23:59:59Z]

**Comment by mfenner** [comment]
Have you tested `1000000`?

**Comment by mfenner** [comment]
And what is the best response if you go over that number: 403 or 301 (redirect to something else)?

**Comment by kjgarza** [comment]
yes

**Comment by mfenner** [comment]
LGTM. I would like to see this running in `test`.

**Pull request merged**
